server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://beibeiyun:123456@replicasecurity:8004/eureka/, http://replica2:8003/eureka/,http://local:8001/eureka/
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
logging:
  level:
    com.beibeiyun.service.UserService: debug
 #多次调用http://localhost:8701/user/1进行测试，可以发现运行在 8201 和 8202 的 user-service 服务交替打印信息
 # 调用http://localhost:8701/user/1进行测试，可以发现返回了服务降级信息。


#  feign:
#    hystrix:
#      enabled: true #在Feign中开启Hystrix
#    compression:
#      request:
#        enabled: false #是否对请求进行GZIP压缩
#        mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
#        min-request-size: 2048 #超过该大小的请求会被压缩
#      response:
#        enabled: false #是否对响应进行GZIP压缩
#  logging:
#    level: #修改日志级别
#      com.macro.cloud.service.UserService: debug