server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://beibeiyun:123456@replicasecurity:8004/eureka/, http://replica2:8003/eureka/,http://local:8001/eureka/
zuul:
  prefix: /proxy #给网关路由添加前缀  http://localhost:8801/proxy/userService/user/1
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  ignored-services: user-service,feign-service #关闭默认路由配置
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  filterClassName:
    filter:
      disable: true   #对过滤器进行禁用的配置
  PreLogFilter:
    pre:
      disable: true   #禁用PreLogFilter的示例配置
management:
  endpoints:
    web:
      exposure:
        include: 'routes'  # http://localhost:8801/actuator/routes 查看简单路由信息 http://localhost:8801/actuator/routes/details 查看详细路由信息