server:
  port: 8004
spring:
  application:
    name: eureka-security-server
  security: #配置SpringSecurity登录用户名和密码
    user:
      name: beibeiyun
      password: 123456
eureka:
  instance:
    hostname: replicasecurity
  client:
    serviceUrl:
      defaultZone: http://replica2:8003/eureka/,http://local:8001/eureka/,http://replica1:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: false
    register-with-eureka: false
