server:
  port: 8001
spring:
  application:
    name: eureka-server #指定服务名称
eureka:
  instance:
    hostname: local #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    serviceUrl:
      defaultZone: http://replica2:8003/eureka/,http://replica1:8002/eureka/
  server:
    enable-self-preservation: false #关闭保护模式
