server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://github.com/beibeiyun/springcloud-config.git
          username: beibeiyun
          password: Gg929517
          clone-on-start: true #开启启动时直接从git获取配置
eureka:
  client:
    service-url:
      defaultZone: http://beibeiyun:123456@replicasecurity:8004/eureka/
